apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-manager
  namespace: task-manager
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: task-manager
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
